$(document).ready(function(){
  $("#aa").hover(function(){
    $("#move").show();
    $(this).draggable();
  });

  $("#aa").click(function(){
    $("#first").show();
    $("#move").css("opacity","0");
    $("#movewords").show();
  });

  $("#first").click(function(){
    $(this).css("opacity",".9");
    $("#second").show();
  });
  $("#second").click(function(){
    $(this).css("opacity",".9");
    $("#first").css("opacity",".8");
    $("#third").show();
  });
  $("#third").click(function(){
    $(this).css("opacity",".9");
    $("#second").css("opacity",".8");
    $("#first").css("opacity",".7");
    $("#four").show();
  });
  $("#four").click(function(){
    $(this).css("opacity",".9");
    $("#third").css("opacity",".8");
    $("#second").css("opacity",".7");
    $("#first").css("opacity",".6");
    $("#five").show();
  });
  $("#five").click(function(){
    $(this).css("opacity",".9");
    $("#four").css("opacity",".8");
    $("#third").css("opacity",".7");
    $("#second").css("opacity",".6");
    $("#first").css("opacity",".5");
    $("#sixth").show();
  });
  $("#sixth").click(function(){
    $(this).css("opacity",".9");
    $("#five").css("opacity",".8");
    $("#four").css("opacity",".7");
    $("#third").css("opacity",".6");
    $("#second").css("opacity",".5");
    $("#first").css("opacity",".4");
    $("#seven").show();
  });
  $("#seven").click(function(){
    $(this).css("opacity",".9");
    $("#sixth").css("opacity",".8");
    $("#five").css("opacity",".7");
    $("#four").css("opacity",".6");
    $("#third").css("opacity",".5");
    $("#second").css("opacity",".4");
    $("#first").css("opacity",".3");
    $("#eight").show();
  });
  $("#eight").click(function(){
    $(this).css("opacity",".9");
    $("#seven").css("opacity",".8");
    $("#sixth").css("opacity",".7");
    $("#five").css("opacity",".6");
    $("#four").css("opacity",".5");
    $("#third").css("opacity",".4");
    $("#second").css("opacity",".3");
    $("#first").css("opacity",".2");
    $("#nine").show();
  });
  $("#nine").click(function(){
    $(this).css("opacity",".9");
    $("#eight").css("opacity",".8");
    $("#seven").css("opacity",".7");
    $("#sixth").css("opacity",".6");
    $("#five").css("opacity",".5");
    $("#four").css("opacity",".4");
    $("#third").css("opacity",".3");
    $("#second").css("opacity",".2");
    $("#first").css("opacity",".1");
    $("#ten").show();
  });
})
